In [1]:
import numpy as np

# Array İşlemleri

In [2]:
# * operatörü iki list arasında tanımsızdır, hata verir

In [3]:
a=[1,2,3]
b=[2,4,6]
a*b

TypeError: can't multiply sequence by non-int of type 'list'

* List ile integer çarpılırsa ard arda concatenation yapar

In [4]:
[2,4,8]*3

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [5]:
[2,4,6]+[2,4,6]+[2,4,6]

[2, 4, 6, 2, 4, 6, 2, 4, 6]

* `*` operatörü iki numpy arrayi arasında tanımlıdır, element-wise(eleman bazlı) çarpma yapar

In [6]:
x=np.array([1,2,3])
y=np.array([2,4,8])
x*y

array([ 2,  8, 24])

* element-wise çarpım yaptığı için çarpılan iki arrayin eleman sayısı aynı olmalı

In [7]:
x2=np.array([1,2,3])
y2=np.array([2,4,8,10])
x2*y2

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [8]:
a=[1,2,3]
b=[2,4,8]

In [9]:
a+b #concat yapar

[1, 2, 3, 2, 4, 8]

In [10]:
print(x)
print(y)

[1 2 3]
[2 4 8]


In [11]:
x+y

array([ 3,  6, 11])

In [13]:
a

[1, 2, 3]

In [14]:
3*a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [15]:
x

array([1, 2, 3])

In [16]:
x*3

array([3, 6, 9])

* değer güncellemek için

In [17]:
x=x*3

In [18]:
x

array([3, 6, 9])