In [1]:
import numpy as np

# Reshaping
* Önemli nokta reshape yapacağımız yapının yaptıktan sonraki yapıyla aynı eleman sayısına sahip olması, yani sizeları aynı olacak

In [2]:
a=np.arange(1,11)

In [3]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a.ndim

1

In [5]:
a.size

10

In [7]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [9]:
a.reshape(5,2).ndim

2

* Eleman sayısı tutmazsa hata alırım

In [10]:
a.reshape(6,2)

ValueError: cannot reshape array of size 10 into shape (6,2)

### -1 ile Boyuta Karar Vermek

In [11]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### Yeni Boyut Eklemek

In [12]:
a=np.arange(1,11)

In [13]:
a[np.newaxis,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [14]:
a[np.newaxis,:].shape

(1, 10)

In [15]:
#column vector
a[:,np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [16]:
a[:,np.newaxis].shape

(10, 1)

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

* Veya None yazarak yapabiliriz.

In [18]:
a[None,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [19]:
a[:,None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])