In [1]:
import numpy as np

# Concatenation

In [3]:
a=np.array([1,2,3,4])

In [4]:
b=np.array([5,6,7,8])

In [5]:
a

array([1, 2, 3, 4])

In [6]:
b

array([5, 6, 7, 8])

In [7]:
# a ve b güncellenmez
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

* python listlerinide numpy arraylari ile concatenationa sokabiliriz.

In [8]:
l=[10,11]

In [9]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [10]:
l=[10,11,11.2]

In [11]:
np.concatenate([a,b,l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. , 10. , 11. , 11.2])

In [12]:
l=[10,11,"11,2"]

In [13]:
np.concatenate([a,b,l])

array(['1', '2', '3', '4', '5', '6', '7', '8', '10', '11', '11,2'],
      dtype='<U11')

* python tuplelarını da numpy arraylari ile concatenationa sokabiliriz

In [14]:
l=(10,11)

In [15]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

### Size Mismatch

In [16]:
a

array([1, 2, 3, 4])

In [18]:
x=np.array([[1,2,3],
           [4,5,6]])

In [19]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
x.size

6

In [21]:
x.shape

(2, 3)

In [22]:
a.shape

(4,)

In [23]:
#shape mismatch
np.concatenate([x,a])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [24]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [26]:
np.concatenate([x,x],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])