In [1]:
import numpy as np

# Splitting

In [2]:
l=[10,20,30,40,50,60,70,80]

In [3]:
l

[10, 20, 30, 40, 50, 60, 70, 80]

In [5]:
#[0,1][2,3,4,5][6,7]
np.split(l,[2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [6]:
np.split(l,[3,5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]

In [7]:
a=np.array([10,20,30,40,50,60,70,80])

In [8]:
np.split(a,[2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

### Splitin Sonucunu Birden Çok Değişene Eşitleme

In [9]:
a,b=(1,10)

In [10]:
print(a)
print(b)

1
10


In [11]:
x,y,z=np.split(l,[2,6])

In [12]:
x

array([10, 20])

In [13]:
y

array([30, 40, 50, 60])

In [14]:
z

array([70, 80])

### vsplit

In [16]:
a=np.arange(20).reshape(2,10)

In [17]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [18]:
np.vsplit(a,[1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [19]:
np.vsplit(a,[1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### hsplit

In [20]:
a=np.arange(20).reshape(2,10)

In [21]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [22]:
np.hsplit(a,[2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [23]:
np.hsplit(a,[2])[0]

array([[ 0,  1],
       [10, 11]])

In [24]:
np.hsplit(a,[2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [25]:
np.hsplit(a,[2])[0].shape

(2, 2)

In [26]:
np.hsplit(a,[2])[1].shape

(2, 8)

In [27]:
x,y=np.hsplit(a,[2])

In [28]:
x

array([[ 0,  1],
       [10, 11]])

In [29]:
y

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [30]:
x,y,z=np.hsplit(a,[2,4])

In [31]:
x

array([[ 0,  1],
       [10, 11]])

In [32]:
y

array([[ 2,  3],
       [12, 13]])

In [33]:
z

array([[ 4,  5,  6,  7,  8,  9],
       [14, 15, 16, 17, 18, 19]])