In [1]:
import numpy as np

# Sorting

In [2]:
a=np.array([20,32,5,30,10])

In [3]:
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [4]:
a

array([20, 32,  5, 30, 10])

In [5]:
#a yı günceller
a.sort() #inplace (a=np.sort(a) ile aynı)

In [6]:
a

array([ 5, 10, 20, 30, 32])

### argsort

In [7]:
a=np.array([3,1,6,5,4,2])

In [9]:
#küçükten büyüğe sıralanmış elemanların indexlerini döndürür.
idxs=np.argsort(a)

In [10]:
idxs

array([1, 5, 0, 4, 3, 2], dtype=int64)