In [1]:
import numpy as np

# Fancy Indexing
* Şimdiye kadar hep belirli elemanları, belirli kesitlerdeki elemanları, veya belirli sayıda atlaya atlaya elemanları almayı gördük. Fancy indexing ile bir kaç tane belirli indexteki elemanı bana döndür diyebilmiş olacağız.

In [2]:
x=np.arange(1,15)

In [4]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
idxs=[4,5,7,11]

In [6]:
#4,5,7,11 indexteki elemanları döndürür.
x[idxs]

array([ 5,  6,  8, 12])

In [7]:
a=np.arange(12).reshape(3,4)

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a[0:2,1]

array([1, 5])

In [10]:
a[0:2,1].shape

(2,)

In [11]:
a[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [12]:
a[0:2,1:3].shape

(2, 2)

In [13]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
a[0,[1,3]]

array([1, 3])

In [15]:
a[0:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [16]:
a=np.arange(20).reshape(4,5)

In [17]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [18]:
idx1=[1,3,2]

In [19]:
idx2=[3,0,2]

In [20]:
a[idx1,idx2]

array([ 8, 15, 12])

In [21]:
a[idx1][idx2]

IndexError: index 3 is out of bounds for axis 0 with size 3

* Fancy indexing sonucunu belirli değerlere eşitlemek

In [22]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
x[[1,2,3]]=20

In [25]:
x

array([ 1, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
x=np.arange(9)

In [27]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
x[[1,2,5]]=[100,200,300]

In [29]:
x

array([  0, 100, 200,   3,   4, 300,   6,   7,   8])