In [1]:
import numpy as np

# Subarray

In [2]:
a=np.arange(1,21).reshape(4,5)

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
b=a[:2,:3]

In [5]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [6]:
b.ndim

2

In [7]:
b[0,0]=100

In [8]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [9]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

### Copy
* copy() metodunu kullanırsak subarrayin değerinin değişmesi orjinal arrayi etkilemez

In [10]:
a=np.arange(1,21).reshape(4,5)

In [11]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [14]:
b=a[:2,:3].copy()

In [15]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [16]:
b[0,0]=100

In [17]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [18]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])