In [8]:
import numpy as np

# Array Data Tipini Manuel Belirtmek
* Arrayin elemanlarının tipinin ne olacağını özellikle belirtebiliriz.

In [11]:
x=np.array([1,2,3,4.5])

In [12]:
x

array([1. , 2. , 3. , 4.5])

In [13]:
x=np.array([1,2,3,4.5],dtype="int32")

In [14]:
x

array([1, 2, 3, 4])

In [16]:
x=np.array([1,2,3,4.5],dtype="str")

In [17]:
x

array(['1', '2', '3', '4.5'], dtype='<U3')

In [18]:
x=np.array(["a"],dtype="int32")

ValueError: invalid literal for int() with base 10: 'a'

In [19]:
x=np.array(["5"],dtype="int32")

In [20]:
x

array([5])