In [1]:
import numpy as np

# Conditional Indexing

In [2]:
a=np.arange(1,10)

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a<5

array([ True,  True,  True,  True, False, False, False, False, False])

In [5]:
a[a<5]

array([1, 2, 3, 4])

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
filt=a<3

In [9]:
filt

array([ True,  True, False, False, False, False, False, False, False])

In [10]:
a[filt]

array([1, 2])

In [22]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
b=np.array([2,3,3,4,5,61,7,8,11])

In [24]:
b

array([ 2,  3,  3,  4,  5, 61,  7,  8, 11])

In [25]:
a == b

array([False, False,  True,  True,  True, False,  True,  True, False])

In [26]:
a[a==b]

array([3, 4, 5, 7, 8])

In [27]:
b[a==b]

array([3, 4, 5, 7, 8])

In [28]:
#broadcasting
a==[1]

array([ True, False, False, False, False, False, False, False, False])

In [29]:
a==1

array([ True, False, False, False, False, False, False, False, False])

In [30]:
#normalde and or ile kurduğumuz mantığı numpyda kullanamıyoruz.
(a<3) or (a>5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [31]:
(a<3) | (a>5)

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [32]:
a[(a<3) | (a>5)]

array([1, 2, 6, 7, 8, 9])

In [33]:
filt=(a<3) | (a>5)

In [34]:
filt

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [35]:
a[filt]

array([1, 2, 6, 7, 8, 9])

In [40]:
a[(a>3) & (a<=5)]

array([4, 5])

### Filtrenin değili 

In [41]:
a=np.arange(1,21).reshape(4,5)

In [42]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [43]:
filt=a<5

In [44]:
a[filt]

array([1, 2, 3, 4])

In [45]:
filt=(a>5) & (a<9)

In [46]:
a[(!(a>5) & (a<9))]

SyntaxError: invalid syntax (2592924722.py, line 1)

In [47]:
filt

array([[False, False, False, False, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [48]:
~((a>5) & (a<9))

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [49]:
filt=~((a>5) & (a<9))

In [50]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

### Multidimesional Arraylerde Conditional Indexing

In [51]:
a=np.arange(1,21).reshape(4,5)

In [52]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [53]:
type(a)

numpy.ndarray

In [54]:
type(a<7)

numpy.ndarray

In [55]:
a<7

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [56]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [57]:
a[a<7].shape

(6,)

In [58]:
a=np.array([1,2,3,None])

In [59]:
a

array([1, 2, 3, None], dtype=object)

In [60]:
a==None

array([False, False, False,  True])

In [61]:
a[a==None]

array([None], dtype=object)

In [62]:
a=np.arange(-5,3).reshape(2,4)