In [1]:
import numpy as np

# Sum
* Verilen Conditionı kaç elemanın sağladığını bulalım.

In [2]:
a=np.arange(1,21).reshape(4,5)

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [6]:
np.sum(a)

210

In [7]:
filt=a<5

In [8]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [9]:
np.sum(filt)

4

In [10]:
a[filt]

array([1, 2, 3, 4])

In [11]:
np.sum(a[filt])

10

In [12]:
filt=(a>5)&(a<9)

In [13]:
np.sum(filt)

3

In [14]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
a[filt]

array([6, 7, 8])

In [16]:
np.sum(a[(a>5)&(a<9)])

21

In [21]:
filt=~((a>5)&(a<9))

In [22]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
np.sum(~((a>5)&(a<9)))

17

In [24]:
np.sum(a[~((a>5)&(a<9))])

189

### Belirli axis Üzerinde Toplama

In [25]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
np.sum(a,axis=0)

array([34, 38, 42, 46, 50])

In [27]:
np.sum(a,axis=1)

array([15, 40, 65, 90])

In [29]:
a=np.arange(1,21).reshape(4,5)

In [30]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [31]:

 np.sum(a,axis=0) 

array([34, 38, 42, 46, 50])

In [32]:

 np.sum(a,axis=0).shape

(5,)