In [1]:
import numpy as np

# any()
* Herhangi bir eleman verilen şartı sağlıyor mu kontrol etmek

In [2]:
a=np.arange(20).reshape(4,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
a>17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

In [5]:
np.any(a>17)

True

In [6]:
np.any(a>17,axis=0)

array([False, False, False,  True,  True])

In [7]:
np.any(a>17,axis=1)

array([False, False, False,  True])