In [1]:
import numpy as np

# Belirtilen Bir Elemandan Array Oluşturmak

In [3]:
np.full((4,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [4]:
np.full(4,5,5)

TypeError: Cannot interpret '5' as a data type

In [5]:
np.full(4,5)

array([5, 5, 5, 5])

In [6]:
np.full((4,5),"a")

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

In [7]:
np.full((4,5),5.2)

array([[5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2]])

In [9]:
str(5.2)

'5.2'

In [11]:
np.full((4,5),5.2,dtype="str")

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

In [13]:
np.full((4,5),"5.2")

array([['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2']], dtype='<U3')