In [1]:
import numpy as np

# Normal Distribution'dan Çekilmiş Değerler İle Array Oluşturmak
*(mean,std,array size)

In [2]:
np.random.normal(0,1,(4,5))

array([[-2.16301727,  1.07724324, -0.37537914,  1.1375475 , -1.73600839],
       [ 1.3207776 ,  0.22225776, -1.08998107, -0.73521591,  0.79250561],
       [-0.69099323,  0.68709445,  1.04943728, -0.20188369, -0.21836428],
       [-1.4345639 ,  0.9267783 , -0.05939241,  0.16247356, -0.21643077]])

In [3]:
np.random.normal(0,100,(4,5))

array([[   6.48858373,  -59.61312497, -142.08731938,   -7.27339385,
          84.02863875],
       [  95.66984067,  -58.18866467,   43.11915917,   66.53418934,
         151.98746422],
       [ -38.07622987,   68.8519236 ,   99.0788878 , -124.67053194,
          40.13925859],
       [  64.73484626,  177.42075422, -115.70718096,  224.41426912,
        -103.49897969]])

In [5]:
np.random.normal(10,100,(4,5))

array([[ 132.70669752,  130.63520174,   61.58994392,   41.54005147,
          10.66342209],
       [  19.3033181 ,  -82.52951713,   45.74575157, -146.03679149,
        -119.64685102],
       [-169.65452718,   45.72995339,  -16.84189538,   76.02030547,
         138.84294685],
       [  -7.28300234,  -78.00507215,  -43.12369483, -149.35765126,
         163.80287696]])

In [6]:
np.random.normal(10,1,(4,5))

array([[10.04061904, 10.29465601, 10.93241639, 11.52205414,  8.62898158],
       [ 8.75674505, 10.47334408, 11.03005576,  9.4936861 ,  9.93373913],
       [ 8.89979715,  9.6942831 , 10.03398794, 11.13255568,  9.83044563],
       [10.83919559,  8.76742503, 11.81917701, 10.83745364,  9.62150046]])